name: Terraform test reusable

on: 
  workflow_dispatch:
  

jobs: 
   uses: tikenek/github_actions/.github/workflows/terraform-template.yml
   secrets:
     env_aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
     env_aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
     env_github_token: ${{secrets.GITHUB_TOKEN}}
