name: Sync Fork

on:
  workflow_call:
 
  
jobs:
  reusable_workflow_job:
    runs-on: self-hosted
    #environment: production
    steps:
      - uses: tikenek/github_actions/.github/workflows/terraform-template.yml@v1
        with:
          # URL of gitHub public upstream repo
         # upstream_repo: "https://github.com/actions/starter-workflows.git"
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: master #main
          # Branch to merge into downstream
          downstream_branch: master
          # GitHub Bot token
          token: ${{ secrets.GITHUB_TOKEN }}

